###################################################
# +---------------------------------------------+ #
# |             Database Connection             | #
# +---------------------------------------------+ #
###################################################

# CAUTION! Developer mode will drop all database tables on startup. DO NOT USE IN PRODUCTION.
developer-mode: false

# Database connection settings.
mysql:
  host: localhost
  port: 3306
  username: unitedwars
  password: unitedwars
  database: unitedwars

###################################################
# +---------------------------------------------+ #
# |                War Scheduler                | #
# +---------------------------------------------+ #
###################################################

warscheduler-check-interval: 15 # in seconds

geopol-attribute-defaults:
  MOBILIZATION:
    current-value: 20
    max-value: 100
    min-value: 0
    daily-change: 1
  MAX_MERCENARIES:
    current-value: 5
    max-value: 5
    min-value: 0
    daily-change: 0


###################################################
# +---------------------------------------------+ #
# |                 War Settings                | #
# +---------------------------------------------+ #
###################################################

# Ignore these worlds for pvp scoring
world-blacklist:
  - world_arena1
  - world_arena2
  - world_arena3

# Duration of war immunity for towns that come out of a defensice war
war-immunity-duration: 10080 # in minutes

# Settings for different war goals
war-goal-settings:
  skirmish:
    required-rank: mayor
    warmup-time: 10 # in seconds
    duration: 259200 # in seconds
    cost: 30 # mobilisation points
    war-lives: 5
    scorecaps:
      attacker: 
        value: 10000
      defender: 
        value: 10000
  revolt:
    required-rank: mayor
    warmup-time: 10 # in seconds
    duration: 259200 # in seconds
    cost: 30 # mobilisation points
    war-lives: 5
    scorecaps:
      attacker: 
        value: 30000
      defender: 
        value: 30000
  claim-dispute:
    required-rank: leader
    warmup-time: 10 # in seconds
    duration: 259200 # in seconds
    cost: 10 # mobilisation points
    war-lives: 5
    scorecaps:
      claimant: 
        value: 30000
  conquest:
    required-rank: leader
    warmup-time: 10 # in seconds
    duration: 259200 # in seconds
    cost: 30 # mobilisation points
    war-lives: 5
    scorecaps:
      attacker: 
        value: 30000
      defender: 
        value: 30000
  subjugation:
    required-rank: leader
    warmup-time: 10 # in seconds
    duration: 259200 # in seconds
    cost: 30 # mobilisation points
    war-lives: 5
    scorecaps:
      attacker: 
        value: 15000
      defender: 
        value: 15000

military-ranks:
  default: # civilian rank, players with no assigned military towny rank
    score-multiplier: 0.0
    level: town
    unique: false
  militia:
    score-multiplier: 0.9
    level: town
    unique: false
  soldier:
    score-multiplier: 1.0
    level: town
    unique: false
  officer:
    score-multiplier: 1.1
    level: town
    unique: false
  general:
    level: nation
    score-multiplier: 1.2
    unique: true

siege-settings:
  # Optional visual markers shown on Pl3xmap at the location of capture chunks during wars
  capture-markers: 
    use: true
    layer-key: "unitedwars"
    layer-name: "Wars"
    marker: "siege"

  # number of schematics to randomly pick from when placing war camps. Set to 0 to disable placement.
  warcamp-templates: 5
  # If true, sieges and griefing will always be active regardless of whether players of a particular
  # war side are online or not
  override-activity-requirement: false
  # If sieging from the border is required, players can only start capturing chunks that are
  # either adjacent to wilderness, or adjacent to already occupied chunks
  require-siege-from-border: true
  # If true, the health decay and restoration is applied per player in the majority:
  # 5 attackers vs. 2 defenders = 3 player majority for attackers = 3 * health decay rate per war tick
  # If false, the health decay and restoration only apply once per team in the majority
  use-superiority-multiplier: true
  # The amount of HP a chunk loses when the attackers are in a majority
  health-decay-rate: 1
  # The amount of HP a chunk heals when the defenders are in a majority
  health-restore-rate: 1
  # Initial max health points for chunk types
  chunk-max-health:
    default: 
      value: 3
    home: 
      value: 50
    region-home: 
      value: 500
    warcamp: 
      value: 100
    fortress: 
      value: 250
  # Commands that players can't use while sieges are ongoing (i.e. enemies are online)
  disabled-commands:
    - "rtp"
    - "tfly"
    - "pwarp"
    - "warp"
    - "ud warp"

###################################################
# +---------------------------------------------+ #
# |               Score settings                | #
# +---------------------------------------------+ #
###################################################

score-settings:
  activity: 1
  pvp-kill:
    leader-kill-bonus-multiplier: 1.5
    rank-scores:
      default: 
        value: 0
      militia: 
        value: 10
      soldier: 
        value: 100
      officer: 
        value: 200
      general: 
        value: 500
  chunk-capture:
    default: 
        value: 10
    home: 
        value: 500
    region-home: 
        value: 500
    warcamp: 
        value: 250
    fortress: 
        value: 250

notification-settings:
  ACTIVITY:
    silent: true
    message: score-activity
  PVP_KILL:
    silent: false
    message: score-pvp-kill
  PVP_KILL_LEADER:
    silent: false
    message: score-pvp-kill-leader
  SIEGE_CHUNK_CAPTURE:
    silent: false
    message: score-siege-capture-default

###################################################
# +---------------------------------------------+ #
# |                  War Books                  | #
# +---------------------------------------------+ #
###################################################

war-book:
  name: "Unnamed War"
  content: "Replace this page with a brief description of your war reasons.\n\n"
  lore:
    - ""
    - "<yellow>Rename <gray>this book at an anvil"
    - "<gray>to set the name of the war."
    - "<yellow>Right-click <gray>this book to write"
    - "<gray>your reasoning behind the <yellow>war."
    - ""